# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kiven/code/my_utils/python/license_control/license_control/parser/parser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CheckLicenseDialog(object):
    def setupUi(self, CheckLicenseDialog):
        CheckLicenseDialog.setObjectName("CheckLicenseDialog")
        CheckLicenseDialog.resize(480, 270)
        CheckLicenseDialog.setStyleSheet("QGroupBox { border: 1px solid gray; border-radius: 4px; margin-top: 0.5em; font-weight: normal; } QGroupBox::title {subcontrol-origin: margin; left: 10px; padding: 0 3px 0 3px;}")
        self.gridLayout_2 = QtWidgets.QGridLayout(CheckLicenseDialog)
        self.gridLayout_2.setContentsMargins(15, 15, 15, 10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(CheckLicenseDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.license_file_line = QtWidgets.QLineEdit(CheckLicenseDialog)
        self.license_file_line.setObjectName("license_file_line")
        self.horizontalLayout_2.addWidget(self.license_file_line)
        self.open_file_button = QtWidgets.QPushButton(CheckLicenseDialog)
        self.open_file_button.setObjectName("open_file_button")
        self.horizontalLayout_2.addWidget(self.open_file_button)
        self.activate_button = QtWidgets.QPushButton(CheckLicenseDialog)
        self.activate_button.setObjectName("activate_button")
        self.horizontalLayout_2.addWidget(self.activate_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(CheckLicenseDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(10, 20, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.activation_state_label = QtWidgets.QLabel(self.groupBox)
        self.activation_state_label.setText("")
        self.activation_state_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.activation_state_label.setObjectName("activation_state_label")
        self.gridLayout.addWidget(self.activation_state_label, 4, 1, 1, 1)
        self.license_code_text = QtWidgets.QTextBrowser(self.groupBox)
        self.license_code_text.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.license_code_text.setObjectName("license_code_text")
        self.gridLayout.addWidget(self.license_code_text, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1, QtCore.Qt.AlignTop)
        self.mac_addr_label = QtWidgets.QLabel(self.groupBox)
        self.mac_addr_label.setText("")
        self.mac_addr_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.mac_addr_label.setObjectName("mac_addr_label")
        self.gridLayout.addWidget(self.mac_addr_label, 2, 1, 1, 1)
        self.product_name_line = QtWidgets.QLabel(self.groupBox)
        self.product_name_line.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.product_name_line.setObjectName("product_name_line")
        self.gridLayout.addWidget(self.product_name_line, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(368, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.close_button = QtWidgets.QPushButton(CheckLicenseDialog)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout.addWidget(self.close_button)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.retranslateUi(CheckLicenseDialog)
        QtCore.QMetaObject.connectSlotsByName(CheckLicenseDialog)

    def retranslateUi(self, CheckLicenseDialog):
        _translate = QtCore.QCoreApplication.translate
        CheckLicenseDialog.setWindowTitle(_translate("CheckLicenseDialog", "License Checker"))
        self.label.setText(_translate("CheckLicenseDialog", "License File"))
        self.open_file_button.setText(_translate("CheckLicenseDialog", "Open..."))
        self.activate_button.setText(_translate("CheckLicenseDialog", "Activate"))
        self.groupBox.setTitle(_translate("CheckLicenseDialog", "License Infomation"))
        self.label_4.setText(_translate("CheckLicenseDialog", "State"))
        self.label_2.setText(_translate("CheckLicenseDialog", "Mac Addr."))
        self.label_3.setText(_translate("CheckLicenseDialog", "Name"))
        self.label_6.setText(_translate("CheckLicenseDialog", "Code"))
        self.product_name_line.setText(_translate("CheckLicenseDialog", "SCI"))
        self.close_button.setText(_translate("CheckLicenseDialog", "Close"))
